version: '3.8'  # Specify the version of Docker Compose

services:
  my_app:
    build: .
    container_name: flask_app
    ports:
      - "80:80"  # Enclose port mapping in quotes
    networks:
      - techpronet
    depends_on:
      - database
    restart: always

  database:
    image: mysql:5.7  # Remove the space before the version number
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
    networks:
      - techpronet
    volumes:
      - techprovol:/var/lib/mysql  # Remove space before the colon

volumes:
  techprovol:  # Ensure proper indentation

networks:
  techpronet:  # Correct the key from "network" to "networks"

